site_name: Awesome Python
site_url: https://yoqi.githb.io/awesome-python
site_description: A curated list of awesome Python frameworks, libraries and software
site_author: Vinta Chen
repo_name: yoqi/awesome-python
repo_url: https://github.com/yoqi/awesome-python
theme:
  name: material
  palette:
    primary: red
    accent: pink
  language: zh

extra:
  social:
    - type: github
      link: https://github.com/vinta
    - type: twitter
      link: https://twitter.com/vinta
    - type: linkedin
      link: https://www.linkedin.com/in/smart-fish-8ba91519a/
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: 中文
      link: /zh/
      lang: zh
# plugins:
  # - search:
  #   lang: en
google_analytics:
  - UA-510626-7
  - auto
extra_css:
    - css/extra.css
nav:
  - "Life is short, you need Python.": "index.md"
